In [1]:
import numpy as np
import pandas as pd

In [2]:
dataset=pd.read_csv('car_data.csv')
dataset.head()

name  year  selling_price  km_driven    fuel  \
0             Maruti 800 AC  2007          60000      70000  Petrol   
1  Maruti Wagon R LXI Minor  2007         135000      50000  Petrol   
2      Hyundai Verna 1.6 SX  2012         600000     100000  Diesel   
3    Datsun RediGO T Option  2017         250000      46000  Petrol   
4     Honda Amaze VX i-DTEC  2014         450000     141000  Diesel   

  seller_type transmission         owner  
0  Individual       Manual   First Owner  
1  Individual       Manual   First Owner  
2  Individual       Manual   First Owner  
3  Individual       Manual   First Owner  
4  Individual       Manual  Second Owner

In [3]:
dataset.describe()

year  selling_price      km_driven
count  4340.000000   4.340000e+03    4340.000000
mean   2013.090783   5.041273e+05   66215.777419
std       4.215344   5.785487e+05   46644.102194
min    1992.000000   2.000000e+04       1.000000
25%    2011.000000   2.087498e+05   35000.000000
50%    2014.000000   3.500000e+05   60000.000000
75%    2016.000000   6.000000e+05   90000.000000
max    2020.000000   8.900000e+06  806599.000000

In [8]:
dataset['year'].isnull().sum() #checking the number of null values present in each column



0

In [9]:
dataset['owner'].value_counts()

First Owner             2832
Second Owner            1106
Third Owner              304
Fourth & Above Owner      81
Test Drive Car            17
Name: owner, dtype: int64

In [10]:
dataset['transmission'].value_counts()

Manual       3892
Automatic     448
Name: transmission, dtype: int64

In [11]:
dataset['fuel'].value_counts()

Diesel      2153
Petrol      2123
CNG           40
LPG           23
Electric       1
Name: fuel, dtype: int64

In [12]:
dataset['seller_type'].value_counts()

Individual          3244
Dealer               994
Trustmark Dealer     102
Name: seller_type, dtype: int64

In [13]:
#Data encoding

In [15]:
x=dataset.iloc[:, [1,3,4,6]].values
y=dataset.iloc[:, 2].values


In [16]:
#Transforming the catagorical data to numerical data
from sklearn.preprocessing import LabelEncoder
lb=LabelEncoder()
x[:,2]=lb.fit_transform(x[:,2])
lb1=LabelEncoder()
x[:,3]=lb1.fit_transform(x[:, 3])

In [17]:
x

array([[2007, 70000, 4, 1],
       [2007, 50000, 4, 1],
       [2012, 100000, 1, 1],
       ...,
       [2009, 83000, 4, 1],
       [2016, 90000, 1, 1],
       [2016, 40000, 4, 1]], dtype=object)

In [18]:
#Defining the training and the testing set
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test= train_test_split(x,y, test_size=0.2, random_state=0)

print(x_train[:,:])

[[2015 175000 1 1]
 [2012 170000 1 1]
 [2006 110000 4 1]
 ...
 [2016 22000 4 1]
 [2015 70000 1 1]
 [2013 62000 4 1]]


In [19]:
#Training the model
from sklearn.ensemble import RandomForestRegressor
regressor= RandomForestRegressor(n_estimators=300, random_state=0)
regressor.fit(x_train, y_train)

RandomForestRegressor(n_estimators=300, random_state=0)

In [21]:
accuracy=regressor.score(x_test, y_test)
print(accuracy*100,  '%')  #Since the dataset and the features are small in number, the accuracy is not that great.

75.79783473129758 %


In [31]:
#performing a test on given input

#input the new data here
print("Enter the Year, km driven, Fuel type and Transmission type.")
new_data=[]
for i in range (0,2):
  new_data.append(int(input()))
for i in range (0,2):
  new_data.append((input()))

new_data[2]=lb.transform([new_data[2]])[0]
new_data[3]=lb1.transform([new_data[3]])[0]



Enter the Year, km driven, Fuel type and Transmission type.
2019
200
Diesel
Automatic


In [42]:
x=regressor.predict([new_data])
print("Rs.",x.flat[0])



Rs. 3499186.6666666665


In [27]:
#saving and encoder using pickle
import pickle
pickle.dump(regressor, open('regressor.pkl', 'wb'))
pickle.dump(lb, open('lb', 'wb'))
pickle.dump(lb1,open('lb1','wb'))